---

- hosts: all
  become: true
  tasks:

  - name: install updates
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 package and update repository index
    tags: apache,centos,httpd,working
    package:
      name:
        - httpd
        - php
      state: latest


  - name: copy default html file for site
    tags: apache,apache,httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
    
- hosts : db_servers
  become: true
  tasks: 
 
  - name: install mariadb
    tags: centos,db,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
