---

- hosts: all
  become: true
  tasks:

  - name: install updates
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"


- hosts: all
  become: true
  tasks:
  
  - name: add ssh kew for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGfbU3nkz1fV270kOab7K695rVUNhB6nsLThUMs0ZAMa ansible"

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
      



- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 package and update repository index
    tags: apache,centos,httpd,working
    package:
      name:
        - httpd
        - php
      state: latest

  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes      
    when: ansible_distribution == "CentOS"



  - name: copy default html file for site
    tags: apache,apache,httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
    
- hosts : db_servers
  become: true
  tasks: 
 
  - name: install mariadb
    tags: centos,db,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
