---

- name: install splunk enterprise
  hosts: search_heads
  become: yes
  
  tasks:
    - name: create search head cluster
      command: "/opt/splunk/bin/splunk init shcluster-config -auth bar:19072003 -mgmt_uri https://{{ ip_addr }}:8089 -replication_port {{ rep_port }} -replication_factor 3 -conf_deploy_fetch_url http://10.0.0.60:8089 -secret 19072003 -shcluster_label cluster_1"

    - name: restart splunk
      command: "/opt/splunk/bin/splunk restart"
