- name: install apache2 package and update repository index
  tags: apache,centos,httpd,working
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes      
  when: ansible_distribution == "CentOS"



- name: copy default html file for site
  tags: apache,apache,httpd
  copy: 
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
    
