---
    - name: Download splunk enterprise
      get_url:
        url: "https://download.splunk.com/products/splunk/releases/9.2.0.1/linux/splunk-9.2.0.1-d8ae995bf219.x86_64.rpm"		
        dest: "/opt/splunk.rpm"

    - name: Install tar on CentOS server
      ansible.builtin.package:
        name: tar
        state: present 

    - name: Install splunk enterprise
      yum:
        name: "/opt/splunk.rpm" 
        state: present

    - name: Create a splunk group
      group:
        name: splunk
        state: present

    - name: create a splunk user
      user:
        name: splunk
        group: splunk
        home: "/opt/splunk"
        system: yes
        state: present

    - name: Set permissions to splunk user and group
      file:
        path: "/opt/splunk"
        owner: splunk
        group: splunk
        recurse: yes

    - name: generate splunk_config launch file from template
      template:
        src: "launch_conf.j2"
        dest: /opt/splunk/etc/splunk-launch.conf	
 
    - name: generate splunk_config web file from template
      template:
        src: "web_conf.j2"
        dest: /opt/splunk/etc/system/default/web.conf


    - name: open firewall ports
      firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        state: enabled
      with_items:
        - 8000
        - 8089
        - 8191

    - name: restart firewalld
      systemd:
        name: firewalld
        state: restarted
        


    - name: restart splunk
      command: "/opt/splunk/bin/splunk restart"
