---
    - name: Download splunk enterprise
      get_url:
        url: "https://download.splunk.com/products/splunk/releases/9.2.0.1/linux/splunk-9.2.0.1-d8ae995bf219.x86_64.rpm"		
        dest: "/opt/splunk.rpm"

    - name: Install tar on CentOS server
      ansible.builtin.package:
        name: tar
        state: present 

    - name: Install splunk enterprise
      yum:
        name: "/opt/splunk.rpm" 
        state: present

    - name: Create a splunk group
      group:
        name: splunk
        state: present

    - name: create a splunk user
      user:
        name: splunk
        group: splunk
        home: "/opt/splunk"
        system: yes
        state: present

    - name: Set permissions to splunk user and group
      file:
        path: "/opt/splunk"
        owner: splunk
        group: splunk
        recurse: yes
